---
# tasks file for server

- name: Update yum packages
    yum:
      name: "*"
      state: latest

- name: Install required software
  yum: 
    name: httpd
    state: latest

- name: Install required software
  yum: 
    name: php
    state: latest
    
- name: Install required software
  yum: 
    name: php-mysql
    state: latest    

- name: Install required software
  yum: 
    name: mysql-server
    state: latest
