---
# tasks file for server

- name: Update yum packages
    yum:
      name: "*"
      state: latest
      become: yes

- name: Install required software
  yum: name={{ item }} state=present
  become: yes
  with_items:
    - httpd
    - php php-mysql
    - mysql-server
